/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef midRosInterface_CONSTANTS_H
#define midRosInterface_CONSTANTS_H

#include "midRosInterface_types.h"



class midRosInterfaceConstants {
 public:
  midRosInterfaceConstants();

};

extern const midRosInterfaceConstants g_midRosInterface_constants;



#endif
