/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef midRosInterfaces_H
#define midRosInterfaces_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "midRosInterface_types.h"



#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class midRosInterfacesIf {
 public:
  virtual ~midRosInterfacesIf() {}
  virtual void setJntTrajSinglePt(const JointPt& pos) = 0;
};

class midRosInterfacesIfFactory {
 public:
  typedef midRosInterfacesIf Handler;

  virtual ~midRosInterfacesIfFactory() {}

  virtual midRosInterfacesIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(midRosInterfacesIf* /* handler */) = 0;
};

class midRosInterfacesIfSingletonFactory : virtual public midRosInterfacesIfFactory {
 public:
  midRosInterfacesIfSingletonFactory(const boost::shared_ptr<midRosInterfacesIf>& iface) : iface_(iface) {}
  virtual ~midRosInterfacesIfSingletonFactory() {}

  virtual midRosInterfacesIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(midRosInterfacesIf* /* handler */) {}

 protected:
  boost::shared_ptr<midRosInterfacesIf> iface_;
};

class midRosInterfacesNull : virtual public midRosInterfacesIf {
 public:
  virtual ~midRosInterfacesNull() {}
  void setJntTrajSinglePt(const JointPt& /* pos */) {
    return;
  }
};


class midRosInterfaces_setJntTrajSinglePt_args {
 public:

  midRosInterfaces_setJntTrajSinglePt_args(const midRosInterfaces_setJntTrajSinglePt_args&);
  midRosInterfaces_setJntTrajSinglePt_args& operator=(const midRosInterfaces_setJntTrajSinglePt_args&);
  midRosInterfaces_setJntTrajSinglePt_args() {
  }

  virtual ~midRosInterfaces_setJntTrajSinglePt_args() throw();
  JointPt pos;

  void __set_pos(const JointPt& val);

  bool operator == (const midRosInterfaces_setJntTrajSinglePt_args & rhs) const
  {
    if (!(pos == rhs.pos))
      return false;
    return true;
  }
  bool operator != (const midRosInterfaces_setJntTrajSinglePt_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const midRosInterfaces_setJntTrajSinglePt_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class midRosInterfaces_setJntTrajSinglePt_pargs {
 public:


  virtual ~midRosInterfaces_setJntTrajSinglePt_pargs() throw();
  const JointPt* pos;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class midRosInterfaces_setJntTrajSinglePt_result {
 public:

  midRosInterfaces_setJntTrajSinglePt_result(const midRosInterfaces_setJntTrajSinglePt_result&);
  midRosInterfaces_setJntTrajSinglePt_result& operator=(const midRosInterfaces_setJntTrajSinglePt_result&);
  midRosInterfaces_setJntTrajSinglePt_result() {
  }

  virtual ~midRosInterfaces_setJntTrajSinglePt_result() throw();

  bool operator == (const midRosInterfaces_setJntTrajSinglePt_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const midRosInterfaces_setJntTrajSinglePt_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const midRosInterfaces_setJntTrajSinglePt_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class midRosInterfaces_setJntTrajSinglePt_presult {
 public:


  virtual ~midRosInterfaces_setJntTrajSinglePt_presult() throw();

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class midRosInterfacesClient : virtual public midRosInterfacesIf {
 public:
  midRosInterfacesClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  midRosInterfacesClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void setJntTrajSinglePt(const JointPt& pos);
  void send_setJntTrajSinglePt(const JointPt& pos);
  void recv_setJntTrajSinglePt();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class midRosInterfacesProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<midRosInterfacesIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (midRosInterfacesProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_setJntTrajSinglePt(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  midRosInterfacesProcessor(boost::shared_ptr<midRosInterfacesIf> iface) :
    iface_(iface) {
    processMap_["setJntTrajSinglePt"] = &midRosInterfacesProcessor::process_setJntTrajSinglePt;
  }

  virtual ~midRosInterfacesProcessor() {}
};

class midRosInterfacesProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  midRosInterfacesProcessorFactory(const ::boost::shared_ptr< midRosInterfacesIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< midRosInterfacesIfFactory > handlerFactory_;
};

class midRosInterfacesMultiface : virtual public midRosInterfacesIf {
 public:
  midRosInterfacesMultiface(std::vector<boost::shared_ptr<midRosInterfacesIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~midRosInterfacesMultiface() {}
 protected:
  std::vector<boost::shared_ptr<midRosInterfacesIf> > ifaces_;
  midRosInterfacesMultiface() {}
  void add(boost::shared_ptr<midRosInterfacesIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void setJntTrajSinglePt(const JointPt& pos) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->setJntTrajSinglePt(pos);
    }
    ifaces_[i]->setJntTrajSinglePt(pos);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class midRosInterfacesConcurrentClient : virtual public midRosInterfacesIf {
 public:
  midRosInterfacesConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  midRosInterfacesConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void setJntTrajSinglePt(const JointPt& pos);
  int32_t send_setJntTrajSinglePt(const JointPt& pos);
  void recv_setJntTrajSinglePt(const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif



#endif
