/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "midRosInterface_constants.h"



const midRosInterfaceConstants g_midRosInterface_constants;

midRosInterfaceConstants::midRosInterfaceConstants() {
}



